Dev
Janni2006/django-elternsprechtag pull request #26
Opened 2022-10-04 12:47 UTC by baastian

Hier einmal meine neuen Sachen. eig nur, dass die login bar richtig funktioniert

2022-10-04 13:20 UTC, Janni2006 requested changes

2022-10-04 13:20 UTC, Janni2006 commented on authentication/signals.py
> +        send_mail(email_subject, email_body, "admin@jhgcloud.de",
Hier müsste eigentlich weiterhin das mit async_send_mail gemacht werden, weil wir es sonst hinerher vergessen. Die Änderung hatte ja schon so seinen Sinn gehabt

2022-10-04 13:20 UTC, Janni2006 commented
Und lösch bitte einmal alle migrations in allen ordnern

2022-10-04 13:41 UTC, baastian commented on authentication/signals.py
> +        send_mail(email_subject, email_body, "admin@jhgcloud.de",
ja das hatte ich nur gemacht, damit ich weiterhin was ausprobieren kann. sonst komme ich nicht so leicht an die daten ran. können wir natürlich wieder ändern

2022-10-05 16:52 UTC, Janni2006 approved these changes

2022-10-05 16:52 UTC, merged